name: Mirror Repositories
description: Mirror multiple repositories between SCMs which support SSH
branding:
  icon: copy
  color: blue
inputs:
  config:
    description: Path to configuration file
    required: true
  ssh_keys:
    description: Map of SSH ids -> paths to SSH private keys
    required: true
  jobs:
    description: Number of parallel jobs
    required: false
    default: '4'
  strict:
    description: Enable StrictHostKeyChecking
    required: false
    default: 'true'
  debug:
    description: Enable debug logging
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Setup current action path
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        ln -sf $(realpath .) ~/work/_actions/current
    - name: Expose action internals
      uses: ./../../_actions/current/internals
    - name: Setup SSH config
      shell: bash
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
    - name: Setup SSH private keys
      shell: bash
      run: |
        while IFS=':' read -r id path; do
            ln -f "$path" "$HOME/.ssh/$id"
        done < <(yq -I0 'to_entries | .[] | .key + ":" + .value' <<< "${{ inputs.ssh_keys }}")
    - name: Mirror repositories
      shell: bash
      run: |
        yq -oj -I0 '.[]' ${{ inputs.config }} | parallel -j ${{ inputs.jobs }} '${{ github.action_path }}/mirror.sh'
      env:
        DEBUG: ${{ inputs.debug == 'true' && 1 || 0 }}
        UNSAFE_SSH: ${{ inputs.strict == 'true' && 0 || 1 }}
    - name: Cleanup
      shell: bash
      if: always()
      run: |
        rm -f ~/work/_actions/current
        mapfile -t ids < <(yq -I0 'keys | .[]' <<< "${{ inputs.ssh_keys }}")
        rm -f "${ids[@]/#/$HOME/.ssh/}"
